version: '3.0'
services:
  rabbitmq:
    container_name: 'rabbit_f5s'
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=f5s
      - RABBITMQ_DEFAULT_PASS=F5seconds2021
      - RABBITMQ_DEFAULT_VHOST=gateway
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /var/lib/docker/volumes/4a7700e29c28cbe73ec000920a6b74ff15d10e40a26846036d996ac35ed22fab/_data:/var/lib/rabbitmq/
    networks:
      - f5s_loyalty_core
  gotit:
    container_name: gotit_f5s
    image: gotit.f5seconds.vn:v.1.0
    environment:
      - DB_URI_APPLICATION=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - DB_URI_IDENTITY=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VHOST=gateway
      - RABBITMQ_USER=f5s
      - RABBITMQ_PASS=F5seconds2021
      - RABBITMQ_TRANS_REQUEST=transactionReqGotItQueue
      - RABBITMQ_TRANS_RES_SUCCESS=transactionResGotItQueue
      - RABBITMQ_TRANS_RES_FAIL=rabbitTransResGotItFailQueue
      - RABBITMQ_VOUCHER_NOTUSE=voucherGotItNotUsedQueue
      - RABBITMQ_VOUCHER_UPDATESTATUS=voucherGotItUpdateStatusQueue
      - SCHEDULE_TRANSCHECK=*/10 * * * * *
      - GOTIT_URI=https://biz-stg.gotit.vn
      - GOTIT_TOKEN=d084e182915cda011778889ad6d6f7950d1f4880544d6bf7a631d7c4df10fc08
    ports:
      - 5051:5051
    networks:
      - f5s_loyalty_core
    depends_on:
      - rabbitmq
  urbox:
    container_name: urbox_f5s
    image: urbox.f5seconds.vn:v.1.0
    environment:
      - DB_URI_APPLICATION=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - DB_URI_IDENTITY=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VHOST=gateway
      - RABBITMQ_USER=f5s
      - RABBITMQ_PASS=F5seconds2021
      - RABBITMQ_TRANS_REQUEST=transactionReqUrboxQueue
      - RABBITMQ_TRANS_RES_SUCCESS=transactionResUrboxQueue
      - RABBITMQ_TRANS_RES_FAIL=rabbitTransResUrboxFailQueue
      - RABBITMQ_VOUCHER_NOTUSE=voucherUrboxNotUsedQueue
      - RABBITMQ_VOUCHER_UPDATESTATUS=voucherUrboxUpdateStatusQueue
      - SCHEDULE_TRANSCHECK=*/10 * * * * *
      - URBOX_URI=https://sandapi.urbox.dev
      - URBOX_APPID=500000114
      - URBOX_APPSECRET=72bf8db101aa8c41d18cd1c326f7d51a
    ports:
      - 5052:5052
    networks:
      - f5s_loyalty_core
    depends_on:
      - rabbitmq
  gateway:
    container_name: gateway_f5s
    image: gateway.f5seconds.vn:v.1.0
    environment:
      - DB_URI_APPLICATION=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - DB_URI_IDENTITY=server=45.119.80.100;port=3307;database=CoreLoyalty;uid=root;password=f5seconds
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_VHOST=gateway
      - RABBITMQ_USER=f5s
      - RABBITMQ_PASS=F5seconds2021
      - RABBITMQ_PRODUCTSYNC=productSyncQueue
      - PARTNER_URI_GOTIT=http://gotit:5051
      - PARTNER_URI_URBOX=http://urbox:5052
      - SCHEDULE_PRODUCTSYNC=0 0 0 * * *
    ports:
      - 5053:5053
    networks:
      - f5s_loyalty_core
    depends_on:
      - rabbitmq
      - gotit
      - urbox
networks:
  f5s_loyalty_core:
    driver: bridge
